language: php
php: 
- 5.4
- 5.5
- 5.6
- hhvm

install:
- php composer.phar install --dev --no-interaction
- php composer.phar dump-autoload

before_script:
- mkdir -p build/logs

script:
- phpunit -c phpunit.xml

after_script:
- sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php php_simulator/vendor/bin/coveralls -v; fi;'
