language: php
php: 
- 5.4
- 5.5
- 5.6
- hhvm

install:
- curl -s http://getcomposer.org/installer | php
- php composer.phar install --dev --no-interaction

before_script:
- mkdir -p build/logs

script:
- phpunit -c phpunit.xml

after_script:
- sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
